
BUILD_RETRON 		= 1

DUMMY_RELEASE		= 0
KIOSK_RELEASE		= 0

ifeq ($(BUILD_RETRON), 1)
MY_FLAGS = -DBUILD_RETRON -DRETRO_VERSION_TAG=0x52350000
endif

ifeq ($(DUMMY_RELEASE), 1)
MY_FLAGS += -DDUMMY_RELEASE
endif

ifeq ($(KIOSK_RELEASE), 1)
MY_FLAGS += -DKIOSK_RELEASE
endif

LOCAL_CFLAGS += $(MY_FLAGS)
ifneq ($(KERNELRELEASE),)
EXTRA_CFLAGS += $(MY_FLAGS)
else
CFLAGS += $(MY_FLAGS)
endif

