BUILD_RETROFREAK 	= 1
MY_FLAGS = -DBUILD_RETROFREAK -DRETRO_VERSION_TAG=0x52460000

LOCAL_CFLAGS += $(MY_FLAGS)
ifneq ($(KERNELRELEASE),)
EXTRA_CFLAGS += $(MY_FLAGS)
else
CFLAGS += $(MY_FLAGS)
endif
